package adapter

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strconv"
	"strings"

	"github.com/makemore/machine/pkg/images"
	"github.com/makemore/machine/pkg/machinefile"
)

// LimaAdapter implements Adapter for Linux using Lima
type LimaAdapter struct{}

// NewLimaAdapter creates a new Lima adapter
func NewLimaAdapter() *LimaAdapter {
	return &LimaAdapter{}
}

// Create creates a Lima VM
func (l *LimaAdapter) Create(mf *machinefile.Machinefile) error {
	// Generate Lima YAML config
	limaConfig, err := l.generateLimaConfig(mf)
	if err != nil {
		return err
	}

	// Write to temp file
	configPath := filepath.Join(os.TempDir(), fmt.Sprintf("machine-%s.yaml", mf.Name))
	if err := os.WriteFile(configPath, []byte(limaConfig), 0644); err != nil {
		return fmt.Errorf("writing lima config: %w", err)
	}

	// Check if VM already exists
	checkCmd := exec.Command("limactl", "list", "--json")
	output, _ := checkCmd.Output()
	if strings.Contains(string(output), fmt.Sprintf(`"name":"%s"`, mf.Name)) {
		fmt.Printf("   VM '%s' already exists, starting...\n", mf.Name)
		startCmd := exec.Command("limactl", "start", mf.Name)
		startCmd.Stdout = os.Stdout
		startCmd.Stderr = os.Stderr
		return startCmd.Run()
	}

	// Create and start VM, disabling the interactive terminal
	cmd := exec.Command("limactl", "start", "--tty=false", "--name", mf.Name, configPath)
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	return cmd.Run()
}

// generateLimaConfig generates Lima YAML from Machinefile
func (l *LimaAdapter) generateLimaConfig(mf *machinefile.Machinefile) (string, error) {
	memoryGB := strings.TrimSuffix(strings.ToLower(mf.Resources.Memory), "gb")

	manifest, err := images.LoadManifest()
	if err != nil {
		return "", fmt.Errorf("loading image manifest: %w", err)
	}

	x86URL, armURL, err := manifest.ResolveImageBothArch(mf.Image)
	if err != nil {
		return "", fmt.Errorf("resolving image: %w", err)
	}

	config := fmt.Sprintf(`# Generated by machine CLI
images:
  - location: "%s"
    arch: "x86_64"
  - location: "%s"
    arch: "aarch64"

cpus: %d
memory: "%sGiB"

containerd:
  system: false
  user: false

mounts: []
`, x86URL, armURL, mf.Resources.CPU, memoryGB)

	// Add port forwards
	if len(mf.Expose) > 0 {
		config += "\nportForwards:\n"
		for _, port := range mf.Expose {
			config += fmt.Sprintf("  - guestPort: %d\n    hostPort: %d\n", port, port)
		}
	}

	return config, nil
}

// getInstallCommand returns the correct install command for the given package manager
func (l *LimaAdapter) getInstallCommand(pm, pkg string) string {
	switch pm {
	case "apt":
		return fmt.Sprintf("sudo apt-get update -qq && sudo apt-get install -y %s", pkg)
	case "pacman":
		return fmt.Sprintf("sudo pacman -Syu --noconfirm %s", pkg)
	case "yum":
		return fmt.Sprintf("sudo yum install -y %s", pkg)
	case "apk":
		return fmt.Sprintf("sudo apk add %s", pkg)
	default:
		// Default to apt-get for unknown package managers
		return fmt.Sprintf("sudo apt-get update -qq && sudo apt-get install -y %s", pkg)
	}
}

// Provision runs setup steps inside the VM
func (l *LimaAdapter) Provision(mf *machinefile.Machinefile) error {
	// Use the shared provisioning pipeline via LimaRunner
	// This handles all v0.2.0 features: harden, swap, users, services,
	// reverse_proxy, first-class installs (docker, postgres, nodejs), etc.
	run := &LimaRunner{Name: mf.Name}
	return provisionAll(mf, run, "127.0.0.1", true)
}

// Run executes run commands
func (l *LimaAdapter) Run(mf *machinefile.Machinefile) error {
	for _, step := range mf.Run {
		if step.Cmd != "" {
			fmt.Printf("   ▶️  %s\n", step.Cmd)
			if err := l.execInVM(mf.Name, step.Cmd); err != nil {
				return err
			}
		}
	}
	return nil
}

// execInVM executes a command inside the Lima VM
func (l *LimaAdapter) execInVM(name, command string) error {
	cmd := exec.Command("limactl", "shell", name, "bash", "-c", command)
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	return cmd.Run()
}

// Stop stops the VM
func (l *LimaAdapter) Stop(mf *machinefile.Machinefile) error {
	cmd := exec.Command("limactl", "stop", mf.Name)
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	return cmd.Run()
}

// Destroy deletes the VM
func (l *LimaAdapter) Destroy(mf *machinefile.Machinefile) error {
	cmd := exec.Command("limactl", "delete", "--force", mf.Name)
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	return cmd.Run()
}

// Connect opens an SSH session
func (l *LimaAdapter) Connect(mf *machinefile.Machinefile) error {
	cmd := exec.Command("limactl", "shell", mf.Name)
	cmd.Stdin = os.Stdin
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	return cmd.Run()
}


// Status prints the current status of the VM
func (l *LimaAdapter) Status(mf *machinefile.Machinefile) error {
	cmd := exec.Command("limactl", "list", mf.Name, "--format",
		"{{.Name}}\t{{.Status}}\t{{.Arch}}\t{{.CPUs}}\t{{.Memory}}\t{{.Disk}}\t{{.Dir}}")
	output, err := cmd.Output()
	if err != nil {
		return fmt.Errorf("machine '%s' not found (has it been created?)", mf.Name)
	}

	result := strings.TrimSpace(string(output))
	if result == "" {
		return fmt.Errorf("machine '%s' not found (has it been created?)", mf.Name)
	}

	parts := strings.Split(result, "\t")
	if len(parts) < 6 {
		// Fallback: just print raw output
		fmt.Println(result)
		return nil
	}

	status := parts[1]
	statusIcon := "⚪"
	switch status {
	case "Running":
		statusIcon = "🟢"
	case "Stopped":
		statusIcon = "🔴"
	}

	fmt.Printf("%s  Machine: %s\n", statusIcon, parts[0])
	fmt.Printf("   Status:  %s\n", status)
	fmt.Printf("   Arch:    %s\n", parts[2])
	fmt.Printf("   CPUs:    %s\n", parts[3])
	fmt.Printf("   Memory:  %s\n", humanizeBytes(parts[4]))
	fmt.Printf("   Disk:    %s\n", humanizeBytes(parts[5]))

	return nil
}

// humanizeBytes converts a byte count string to a human-readable format
func humanizeBytes(s string) string {
	bytes, err := strconv.ParseInt(strings.TrimSpace(s), 10, 64)
	if err != nil {
		return s
	}
	const gb = 1024 * 1024 * 1024
	const mb = 1024 * 1024
	if bytes >= gb {
		return fmt.Sprintf("%.1f GiB", float64(bytes)/float64(gb))
	}
	return fmt.Sprintf("%.0f MiB", float64(bytes)/float64(mb))
}

// Info returns structured machine info
func (l *LimaAdapter) Info(mf *machinefile.Machinefile) (*MachineInfo, error) {
	cmd := exec.Command("limactl", "list", mf.Name, "--format",
		"{{.Name}}\t{{.Status}}\t{{.Arch}}\t{{.CPUs}}\t{{.Memory}}\t{{.Disk}}")
	output, err := cmd.Output()
	if err != nil {
		return nil, fmt.Errorf("VM '%s' not found", mf.Name)
	}
	parts := strings.Split(strings.TrimSpace(string(output)), "\t")
	if len(parts) < 4 {
		return nil, fmt.Errorf("unexpected lima output")
	}
	cpus := 0
	fmt.Sscanf(parts[3], "%d", &cpus)
	return &MachineInfo{
		Name:     parts[0],
		Status:   strings.ToLower(parts[1]),
		Provider: "local",
		OS:       "linux",
		CPUs:     cpus,
	}, nil
}